name: Update generated artifacts

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Update generated artifacts
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Update generated artifacts
      run: |
        go mod tidy
        make generate
        make manifests

        git config user.name "zdenko-kovac"
        git config user.email "zdenko.kovac@sap.com"
        git add -A
        git commit -m "Update generated artifacts"
        git push
